name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: TAM_FRONTEND  # 所有步骤默认在此目录执行

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.17.0"
          cache: "npm"
          cache-dependency-path: "TAM_FRONTEND/package-lock.json"

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Decrypt .env.vault
        env:
          DOTENV_KEY: ${{ secrets.ENV_PASSWORD }}
        run: npx dotenv-vault decrypt .env.vault .env.production  # 直接运行命令，无需 cd

      - name: Build the project
        run: npm run build

      - name: Remove decrypted .env files
        run: rm -f .env.production

      - name: Deploy to production
        run: npm run deploy